### ISSUE TITLE
WAF ACL Logs: Look into redacting authentication headers

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/cloud-based-sensor#123]
Some CDS applications use headers to validate authorization to their service. WAF ACL's support redacting fields before they're logged.

Decide whether headers should be redacted before their logged. Will there be an impact to assessing security risks if we or CCCS is unable to view authorization headers used as part of an attack sequence.

**Comment by patheard** [comment]
As part of onboarding Notify, the `Authorization` header has been redacted to hide the user's api-key:
https://github.com/cds-snc/notification-terraform/blob/d5da037344ac9b64f8948c6474fdd68db9c29137/aws/eks/waf.tf#L279-L282

**Comment by patheard** [comment]
Authorization header has been redacted from Forms as well.
